# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['function', 'say_hello']

# Cell
def function():
    pass


# Cell
def say_hello(to):
    "say hello to somebody"
    return f'Hello {to}'

